version: '2'
volumes:
  mysql-data:
    driver: local
services:
  mysql:
    image: mysql:5.7
    container_name: teste-mlearn-database
    volumes:
    - mysql-data:/var/lib/mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=mlearn
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
  app:
    image: ambientum/php:7.3-nginx
    container_name: app-mlearn
    volumes:
    - .:/var/www/app
    ports:
    - "80:8080"
    links:
    - mysql
