<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Telefone</th>
            <th scope="col">Nível</th>
        </tr>
    </thead>
    <tbody>

        <?php
        foreach ($this->view->dados as $usuario) {
        ?>
            <tr>
                <th scope="row"><?= $usuario->__get('id') ?></th>
                <td><a href="/usuario?id=<?= $usuario->__get('id') ?>"><?= $usuario->__get('nome') ?></a></td>
                <td><?= $usuario->__get('tel') ?></td>
                <td>
                    <?= $usuario->__get('level') ?>
                </td>
            </tr>
        <?php
        }


        ?>
    </tbody>
</table>

<script>
    $('#usuarios').addClass('active')

    $('#btnUpIcon').on('click', e => {
        alert('a')
    })
    $('#btnDownIcon').on('click', e => {
        alert('b')
    })
</script>